server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/application/**
     discovery:
       locator:
         enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
