server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
